export class TreeItem {
  id: any = '' // will be autogenerated if omitted
  parent: any = ''
  text: string = '' // node text
  icon: string = '' // string for custom
  state: {
    opened: boolean // is the node open
    disabled: boolean // is the node disabled
    selected: boolean // is the node selected
  } = { opened: false, disabled: false, selected: false }
  children: TreeItem[] = []
}
