import '../dist/NBtn.js'
import '../dist/NCheckbox.js'
import '../dist/NDataTable.js'
import '../dist/NDropDownList.js'
import '../dist/NDropDownTable.js'
import '../dist/NDropDownTree.js'
import '../dist/NForm.js'
import '../dist/NIcon.js'
import '../dist/NModal.js'
import '../dist/NOverlay.js'
import '../dist/NPagination.js'
import '../dist/NRadio.js'
import '../dist/NRadioGroup.js'
import '../dist/NSelect.js'
import '../dist/NSelect2.js'
import '../dist/NTab.js'
import '../dist/NTextBox.js'
import '../dist/NTimeSelector.js'
import '../dist/NTree.js'

Vue.component('NBtn', NBtn)
Vue.component('NCheckbox', NCheckbox)
Vue.component('NDataTable', NDataTable)
Vue.component('NDropDownList', NDropDownList)
Vue.component('NDropDownTable', NDropDownTable)
Vue.component('NDropDownTree', NDropDownTree)
Vue.component('NForm', NForm)
Vue.component('NIcon', NIcon)
Vue.component('NModal', NModal)
Vue.component('NOverlay', NOverlay)
Vue.component('NPagination', NPagination)
Vue.component('NRadio', NRadio)
Vue.component('NRadioGroup', NRadioGroup)
Vue.component('NSelect', NSelect)
Vue.component('NSelect2', NSelect2)
Vue.component('NTab', NTab)
Vue.component('NTextBox', NTextBox)
Vue.component('NTimeSelector', NTimeSelector)
Vue.component('NTree', NTree)
